language: node_js
node_js:
- '0.12'
branches:
  only:
  - raw
before_install:
- npm install -g hexo
- npm install -g hexo-cli

before_script:
- git config --global user.name 'StartEnd'
- git config --global user.email '858965877@qq.com'
- sed -i'' "s~git@github.com:StartEnd/StartEnd.github.io.git~https://${GitHubKEY}:x-oauth-basic@github.com/StartEnd/StartEnd.github.io.git~" _config.yml
install:
- npm install
script:
- hexo generate
after_success:
- hexo deploy
