language: node_js
node_js:
- '4'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_30329b685338_key -iv $encrypted_30329b685338_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(68503106ffcae45a4dc655cccfd61f037ce704fb)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'StartEnd'
- git config --global user.email 858965877@qq.com
cache:
  directories:
  - node_modules
install:
- npm install hexo-cli -g
- npm install
script:
- hexo clean
- hexo g
- hexo d
